services:
  - type: web
    name: home-app-keeper
    env: node
    buildCommand: npm install && npm run build:full
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000